default_config:
mobile_app:

cloud:
ios:

tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include template.yaml
#  - !include template.yaml
#  - !include template_issues.yaml

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    -  /hacsfiles/lovelace-card-mod/card-mod.js?hacstag=190927524421
wake_on_lan:
media_source:

homeassistant:
  media_dirs:
    local: /media

logger:
  default: error
  logs:
    rflink: debug

browser:



alarm_control_panel:
  - platform: manual
    name: Shed Alarm
    arming_time: 5
    delay_time: 5
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0

cover:
  - platform: template
    covers:
      garage_door:
        device_class: garage
        friendly_name: Shed Yard
        value_template: "{{ is_state('light.truck_yard', 'on') }}"
        open_cover:
          service: light.turn_on
          target:
            entity_id: light.truck_yard
        close_cover:
          service: light.turn_off
          target:
            entity_id: light.truck_yard


camera:
  - platform: ffmpeg
    name: Sdrive Sub
    input: >-
      -rtsp_transport tcp -i
      rtsp://!secret camera_user:!secret camera_password@192.168.1.113:554/h264Preview_01_sub

  - platform: ffmpeg
    name: SDrive Main
    input: >-
      -rtsp_transport tcp -i
      rtsp://!secret camera_user:!secret camera_password@192.168.1.113:554/

  - platform: ffmpeg
    name: STyard Sub
    input: >-
      -rtsp_transport tcp -i
      rtsp://!secret camera_user:!secret camera_password@192.168.1.89:554/h264Preview_01_sub

  - platform: ffmpeg
    name: STyard Main
    input: >-
      -rtsp_transport tcp -i
      rtsp://!secret camera_user:!secret camera_password@192.168.1.89:554/h264Preview_01_main

  - platform: ffmpeg
    name: HDrive Sub
    input: >-
      -rtsp_transport tcp -i
      rtsp://!secret camera_user:!secret camera_password@192.168.1.93:554/h264Preview_01_sub

  - platform: ffmpeg
    name: Hdrive Main
    input: >-
      -rtsp_transport tcp -i
      rtsp://!secret camera_user:!secret camera_password@192.168.1.93:554/h264Preview_01_main

  - platform: ffmpeg
    name: FDoor Sub
    input: >-
      -rtsp_transport tcp -i
      rtsp://!secret camera_user:!secret camera_password@192.168.1.112:554/h264Preview_01_sub

  - platform: ffmpeg
    name: FDoor Main
    input: >-
      -rtsp_transport tcp -i
      rtsp://!secret camera_user:!secret camera_password@192.168.1.112:554/h264Preview_01_main

  - platform: ffmpeg
    name: SEntry Sub
    input: >-
      -rtsp_transport tcp -i
      rtsp://!secret camera_user:!secret camera_password@192.168.1.107:554/h264Preview_01_sub

  - platform: ffmpeg
    name: SEntry Main
    input: >-
      -rtsp_transport tcp -i
      rtsp://!secret camera_user:!secret camera_password@192.168.1.107:554/h264Preview_01_main

#spotcast:
#  sp_dc: !secret spotcast_sp_dc
#  sp_key: !secret spotcast_sp_key

notify:
  - platform: file
    name: stock
    filename: stock.csv
    timestamp: true

  - platform: file
    name: STOCK_DATA
    filename: /config/www/stock_data.txt

  - platform: file
    name: STOCK_SCALE_DATA
    filename: /config/www/stock-scale-data.txt

  - platform: group
    name: Owners
    services:
      - action: mobile_app_jezza_iphone_13
      - action: mobile_app_sm_g780g

sensor:
  - platform: files
    folder: /media/shed_driveway
    filter: "**/*.jpg"
    name: Shed Drive Photos
    sort: date
    recursive: true

  - platform: files
    folder: /media/house_front_door
    filter: "**/*.jpg"
    name: House Front Door Photos
    sort: date
    recursive: false

  - platform: files
    folder: /media/house_driveway
    filter: "**/*.jpg"
    name: House Driveway Photos
    sort: date
    recursive: true

  - platform: files
    folder: /media/shed_mancave
    filter: "**/*.jpg"
    name: Shed Mancave Photos
    sort: date
    recursive: true

  - platform: files
    folder: /media/shed_truckyard
    filter: "**/*.jpg"
    name: Shed Truckyard Photos
    sort: date
    recursive: true

  - platform: statistics
    name: Wind Bearing 3hr Average
    entity_id: sensor.gw2000c_v2_1_8_wind_direction
    state_characteristic: mean
    sampling_size: 30
    max_age:
      hours: 3

  - platform: statistics
    name: Wind Speed 3hr Average
    entity_id: sensor.gw2000c_v2_1_8_wind_speed
    state_characteristic: mean
    sampling_size: 30
    max_age:
      hours: 3

  - platform: statistics
    name: Rain Rate 5min Window
    entity_id: sensor.gw2000c_v2_1_8_yearly_rain_rate_piezo
    state_characteristic: change
    max_age:
      minutes: 5
    sampling_size: 5
    precision: 1

  - platform: statistics
    name: Daily Power Cost Stats
    entity_id: sensor.current_daily_power_cost
    state_characteristic: mean
    sampling_size: 24
    max_age:
      hours: 24

  - platform: statistics
    name: Water Hourly Stats
    entity_id: sensor.water_retic_control_retic_current_hour_2
    state_characteristic: mean
    sampling_size: 24
    max_age:
      hours: 24

  - platform: time_date
    display_options:
      - date

  
utility_meter:
  retic_monthly:
    source: sensor.water_retic_control_retic_current_hour_2
    cycle: monthly
    offset:
      days: 20

