esphome:
  name: light_middle
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout
  
wifi:
  ssid: "hfpshed"
  password: "hillview199@"
      
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Light Middle Fallback Hotspot"
    password: "hillview199@"

captive_portal:

# Enable logging
logger:
  baud_rate: 0

uart:
  rx_pin: RX
  baud_rate: 4800

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Light Middle Button"
    on_press:
      - switch.toggle: fakebutton
  - platform: template
    name: "Light Middle Running"
    filters:
      - delayed_off: 15s
    lambda: |-
      if (isnan(id(power).state)) {
        return {};
      } else if (id(power).state > 0.004) {
        // Running
        return true;
      } else {
        // Not running
        return false;
      }
switch:
  - platform: template
    name: "Light Middle Relay"
    optimistic: true
    id: fakebutton
    turn_on_action:
    - switch.turn_on: relay
    - light.turn_on: led
    turn_off_action:
    - switch.turn_off: relay
    - light.turn_off: led
  - platform: gpio
    id: relay
    pin: GPIO12

output:
  - platform: esp8266_pwm
    id: pow_blue_led
    pin:
      number: GPIO13
      inverted: True

light:
  - platform: monochromatic
    output: pow_blue_led
    id: led

sensor:

  - platform: cse7766
    update_interval: 30s
    current:
      name: "Light Middle Current"
    voltage:
      name: "Light Middle Voltage"
    power:
      name: "Light Middle Power"
      id: power
      filters:
      - multiply: 0.001
      unit_of_measurement: kW
      on_value_range:
        - above: 0.004
          then:
            - light.turn_on: led
        - below: 0.003
          then:
            - light.turn_off: led
           
  - platform: total_daily_energy
    name: "Light Middle Daily kWh"
    id: daily_kw
    power_id: power

time:
  - platform: sntp
    id: my_time
    on_time:
      seconds: 0
      minutes: 0
      hours: 0
      then:
        lambda: |-
          id(daily_kw).publish_state(0);
