esphome:
  name: mancave_dairy
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "hfpshed"
  password: "hillview199@"
    
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Mancave Dairy Fallback Hotspot"
    password: "hillview199@"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

substitutions:
  update_interval_5: 5s
  update_interval_10: 10s
  update_interval_300: 300s

interval:
  - interval: ${update_interval_5}
    then:
      - if:   
          condition:
            light.is_on: mancave_dairy
          then:
            - component.update: mancave_domestic_watts

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: mancave_dairy_touch
    on_press:
     - light.toggle: mancave_dairy
  

output:
  
  - platform: gpio
    pin: GPIO12
    id: relay1
    
  # Register the blue LED as a dimmable output ....
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: True

light:
  
  - platform: binary
    name: Mancave Dairy
    id: mancave_dairy
    output: relay1
    
  # ... and then make a light out of it.
  - platform: monochromatic
    id: light_dairy_led
    output: blue_led

sensor:
  
  - platform: template
    name: "Mancave Domsetic Watts"
    id: mancave_domestic_watts
    update_interval: ${update_interval_300}
    unit_of_measurement: "Watts"
    lambda: |-
      if (id(mancave_dairy).current_values.is_on()){
        id(light_power) += 0.0375;
        return id(light_power);
      } else {
        return {};
      }

time:
  - platform: sntp
    id: my_time
    on_time:
      seconds: 0
      minutes: 0
      hours: 0
      then:
        lambda: |-
          id(light_power) = 0;
          id(mancave_domestic_watts).publish_state(0);
          
globals:
  
  - id: light_power
    type: float
    restore_value: no
    initial_value: '0'